/**
 * Centralized type exports
 * Import from '#shared/types' instead of individual files
 */

// Game types
export {
  GameStatus,
  Role,
  NightActionType,
  NightRole
} from './game'
export type {
  Game,
  Player,
  NightAction,
  DayVote,
  GameEvent
} from './game'

// Database types (generated by Supabase)
export type {
  Database,
  GameSettings
} from './database.types'
